version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: all
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - godot
    - intrange
    - mnd
    - noctx
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - tparallel
    - varnamelen
    - wastedassign
    - wrapcheck
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gosec:
      excludes:
        - G306
      severity: medium
      confidence: medium
    govet:
      enable:
        - shadow
    lll:
      line-length: 150
      tab-width: 4
    misspell:
      locale: US
    staticcheck:
      checks:
        - -SA1019
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - all
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
      dot-import-whitelist:
        - fmt
      http-status-code-whitelist:
        - "200"
        - "400"
        - "404"
        - "500"
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - vendor$
      - third_party$
      - builtin$
      - examples$
