builds:
  - id: tfsort
    main: ./main.go
    binary: tfsort
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: tfsort
    description: "Sort Terraform files"
    homepage: "https://github.com/AlexNabokikh/tfsort"
    tap:
      owner: alexnabokikh
      name: homebrew-tfsort
    commit_author:
      name: Alex Nabokikh
      email: nabokikh@duck.com

chocolateys:
  - name: tfsort
    title: tfsort a CLI utility to sort Terraform variables and outputs
    authors: Alexander Nabokikh
    project_url: https://github.com/AlexNabokikh/tfsort
    url_template: "https://github.com/AlexNabokikh/tfsort/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: "https://rawcdn.githack.com/AlexNabokikh/tfsort/751bf0ae4423f88e33309ccaf9ea2187d04245c3/files/icon.png"
    copyright: 2023 Alexander Nabokikh
    license_url: https://github.com/AlexNabokikh/tfsort/blob/master/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/AlexNabokikh/tfsort
    docs_url: https://github.com/AlexNabokikh/tfsort/blob/master/README.md
    bug_tracker_url: https://github.com/AlexNabokikh/tfsort/issues
    tags: "terraform tf tfsort cli cross-platform"
    summary: A CLI utility to sort Terraform variables and outputs.
    description: |
      {{ .ProjectName }} installer package.
      A CLI utility to sort Terraform variables and outputs.
    release_notes: "https://github.com/AlexNabokikh/tfsort/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
    goamd64: v1

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
