name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  tests:
    name: Tests
    needs: golangci-lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest - temporarily disabled due to github actions bug
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Install dependencies
        run: go mod download
      - name: Go Test
        run: make test

  coverage:
    name: Coverage
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Run tests with coverage
        run: make coverage
      - name: Qlty Coverage Action
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: c.out"
